apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
  labels:
    app: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacamole
          image: guacamole/guacamole:1.5.5
          ports:
          - containerPort: 8080
          env:
          - name: GUACD_HOSTNAME
            value: guacd
          - name: GUACD_PORT
            value: "4822"
          - name: POSTGRES_DATABASE
            value: guacamole
          - name: POSTGRES_USER
            value: guacamole
          - name: POSTGRES_PASSWORD
            value: guacamole
          - name: POSTGRES_HOSTNAME
            value: database
          - name: POSTGRES_PORT
            value: "5432"
          - name: REMOTE_IP_VALVE_ENABLED
            value: "true"
