apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: guacamole-network-policy
spec:
  podSelector:
    matchLabels:
      app: guacamole
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
      - protocol: TCP
        port: 8080


